In [57]:
#Import all relevant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from scipy.stats import zscore

## This statement allows the visuals to render within your Jupyter Notebook.
%matplotlib inline

## Loading the data
We can now load the dataset into pandas using the read_csv() function. This converts the CSV file into a Pandas dataframe.

In [2]:
#Read in the csv file and convert to a Pandas dataframe
df_15 = pd.read_csv("2015.csv")#read the World Happiness file for year 2015
df_16 = pd.read_csv("2016.csv")#read the World Happiness file for year 2016
df_17 = pd.read_csv("2017.csv")#read the World Happiness file for year 2017
df_18 = pd.read_csv("2018.csv")#read the World Happiness file for year 2018
df_19 = pd.read_csv("2019.csv")#read the World Happiness file for year 2019

### Viewing the dataframe
We can get a quick sense of the size of our dataset by using the shape method. This returns a tuple with the number of rows and columns in the dataset.

In [156]:
df_15.head() #View the top five in the data frame in 2015

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [138]:
df_16.head() #View the top five in the data frame in 2016

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [102]:
df_17.head() #View the top five in the dataset in 2017

,Country,Region,Happiness Rank,Happiness Score,Whisker.high,Whisker.low,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
0,Norway,Western Europe,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,Western Europe,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,Western Europe,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,Western Europe,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,Western Europe,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [103]:
df_18.head() #View the top five in the dataset in 2018

,Happiness Rank,Country,Region,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,Western Europe,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,Western Europe,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,Western Europe,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,Western Europe,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [104]:
df_19.head() #View the top five in the dataset in 2019

,Happiness Rank,Country,Region,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,Western Europe,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,Western Europe,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,Western Europe,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,Western Europe,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [16]:
df_15.shape #number of rows and columns in the dataset in 2015

(158, 12)

In [17]:
df_16.shape #number of rows and columns in the dataset in 2016 In this dataset the number of columns is more than 2015 and 2017

(157, 13)

In [18]:
df_17.shape #number of rows and columns in the dataset in 2017

(155, 12)

In [17]:
df_18.shape #number of rows and columns in the dataset in 2018

(156, 9)

In [18]:
df_19.shape #number of rows and columns in the dataset in 2019

(156, 9)

## 1. Data Profiling:
Data profiling is a comprehensive process of examining the data available in an existing dataset and collecting statistics and information about that data.

In [20]:
df_15.info() #Columns with numeric values datatype float and int in 2015

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [21]:
df_16.info() #Columns with numeric values datatype float and int in 2016

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Region                         157 non-null    object
 2   Happiness Rank                 157 non-null    int64
 3   Happiness Score                157 non-null    float64
 4   Lower Confidence Interval      157 non-null    float64
 5   Upper Confidence Interval      157 non-null    float64
 6   Economy (GDP per Capita)       157 non-null    float64
 7   Family                         157 non-null    float64
 8   Health (Life Expectancy)       157 non-null    float64
 9   Freedom                        157 non-null    float64
 10  Trust (Government Corruption)  157 non-null    float64
 11  Generosity                     157 non-null    float64
 12  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.1+ KB

In [22]:
df_17.info() ##Columns with numeric values datatype float and int in 2017

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness.Rank                 155 non-null    int64
 2   Happiness.Score                155 non-null    float64
 3   Whisker.high                   155 non-null    float64
 4   Whisker.low                    155 non-null    float64
 5   Economy..GDP.per.Capita.       155 non-null    float64
 6   Family                         155 non-null    float64
 7   Health..Life.Expectancy.       155 non-null    float64
 8   Freedom                        155 non-null    float64
 9   Generosity                     155 non-null    float64
 10  Trust..Government.Corruption.  155 non-null    float64
 11  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 14.7+ KB

In [59]:
df_18.info() #Columns with numeric values datatype float and int in 2018

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [60]:
df_19.info() #Columns with numeric values datatype float and int in 2019

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [24]:
df_15.describe() #view the count, mean, std, min, 25%, 50%, 75% and the max for each column in 2015

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [25]:
df_16.describe() #view the count, mean, std, min, 25%, 50%, 75% and the max for each column in 2016

,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000
mean,78.980892,5.382185,5.282395,5.481975,0.953880,0.793621,0.557619,0.370994,0.137624,0.242635,2.325807
std,45.466030,1.141674,1.148043,1.136493,0.412595,0.266706,0.229349,0.145507,0.111038,0.133756,0.542220
min,1.000000,2.905000,2.732000,3.078000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.817890
25%,40.000000,4.404000,4.327000,4.465000,0.670240,0.641840,0.382910,0.257480,0.061260,0.154570,2.031710
50%,79.000000,5.314000,5.237000,5.419000,1.027800,0.841420,0.596590,0.397470,0.105470,0.222450,2.290740
75%,118.000000,6.269000,6.154000,6.434000,1.279640,1.021520,0.729930,0.484530,0.175540,0.311850,2.664650
max,157.000000,7.526000,7.460000,7.669000,1.824270,1.183260,0.952770,0.608480,0.505210,0.819710,3.837720

In [26]:
df_17.describe() #view the count, mean, std, min, 25%, 50%, 75% and the max for each column in 2017

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000
mean,78.000000,5.354019,5.452326,5.255713,0.984718,1.188898,0.551341,0.408786,0.246883,0.123120,1.850238
std,44.888751,1.131230,1.118542,1.145030,0.420793,0.287263,0.237073,0.149997,0.134780,0.101661,0.500028
min,1.000000,2.693000,2.864884,2.521116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377914
25%,39.500000,4.505500,4.608172,4.374955,0.663371,1.042635,0.369866,0.303677,0.154106,0.057271,1.591291
50%,78.000000,5.279000,5.370032,5.193152,1.064578,1.253918,0.606042,0.437454,0.231538,0.089848,1.832910
75%,116.500000,6.101500,6.194600,6.006527,1.318027,1.414316,0.723008,0.516561,0.323762,0.153296,2.144654
max,155.000000,7.537000,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.838075,0.464308,3.117485

In [57]:
df_18.describe() #view the count, mean, std, min, 25%, 50%, 75% and the max for each column in 2018

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.375917,0.891449,1.213237,0.597346,0.454506,0.181006,0.113281
std,45.177428,1.119506,0.391921,0.302372,0.247579,0.162424,0.098471,0.097503
min,1.000000,2.905000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.453750,0.616250,1.066750,0.422250,0.356000,0.109500,0.051000
50%,78.500000,5.378000,0.949500,1.255000,0.644000,0.487000,0.174000,0.082000
75%,117.250000,6.168500,1.197750,1.463000,0.777250,0.578500,0.239000,0.139000
max,156.000000,7.632000,2.096000,1.644000,1.030000,0.724000,0.598000,0.457000

In [58]:
df_19.describe() #view the count, mean, std, min, 25%, 50%, 75% and the max for each column in 2019

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

The process of profiling differs slightly for categorical and numerical variables due to their inherent differences.

**The two main types of data are:**
- Quantitative (numerical) data
- Qualitative (categorical) data

### Data Quality Checks
Data quality checks involve the process of ensuring that the data is accurate, complete, consistent, relevant, and reliable. 


**Here are typical steps involved in checking data quality:**

#### 1. Reliability:
Evaluate the data's source and collection process to determine its trustworthiness.

In [58]:
#it is Reliable from gallup world poll

#### 2. Timeliness: 
Ensure the data is up-to-date and reflective of the current situation or the period of interest for the analysis.

#### 3. Consistency: 

Confirm that the data is consistent within the dataset and across multiple data sources. For example, the same data point should not have different values in different places.

In [59]:
#It is consistent and non-inconsistent data

#### 4. Relevance: 
Assess whether the data is appropriate and applicable for the intended analysis. Data that is not relevant can skew results and lead to incorrect conclusions.

**Key considerations for relevance include:**

> 1. Sample Appropriateness: Confirm that your data sample aligns with your analysis objectives. For instance, utilizing data from the Northern region will not yield accurate insights for the Western region of the Kingdom.
>
> 2. Variable Selection: Any column will not be relevant for our analysis, we can get rid of these using the drop() method. We will set the “axis” argument to 1 since we’re dealing with columns, and set the “inplace” argument to True to make the change permanent.

In [ ]:
#In 2015, data were taken from 158 countries, in 2016 from 157 countries, and in 2017 from 155 countries ,in 2018,2019 from 156 countris.

#### 5. Uniqueness: 
Check for and remove duplicate records to prevent skewed analysis results.

In [27]:
df_15.duplicated().sum() #no duplicates values in 2015

0

In [29]:
df_16.duplicated().sum() #no duplicates values in 2016

0

In [30]:
df_17.duplicated().sum() #no duplicates values in 2017

0

In [6]:
df_18.duplicated().sum() #no duplicates values in 2018

0

In [7]:
df_19.duplicated().sum() #no duplicates values in 2019

0

In [66]:
#no duplicates

#### 6. Completeness: 
Ensure that no critical data is missing. This might mean checking for null values or required fields that are empty.

We will start by checking the dataset for missing or null values. For this, we can use the isna() method which returns a dataframe of boolean values indicating if a field is null or not. To group all missing values by column, we can include the sum() method.

In [1]:
#Display number missing values per column

In [31]:
df_15.isnull().sum() #Display number missing values in 2015 # no missing values

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [32]:
df_16.isnull().sum() #Display number missing values in 2016 #no missing values

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Lower Confidence Interval        0
Upper Confidence Interval        0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [33]:
df_17.isnull().sum() #Display number missing values in 2017 #no missing values

Country                          0
Happiness.Rank                   0
Happiness.Score                  0
Whisker.high                     0
Whisker.low                      0
Economy..GDP.per.Capita.         0
Family                           0
Health..Life.Expectancy.         0
Freedom                          0
Generosity                       0
Trust..Government.Corruption.    0
Dystopia.Residual                0
dtype: int64

In [8]:
df_18.isnull().sum() #there is one missing value

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       1
dtype: int64

In [26]:
df_18[df_18['Perceptions of corruption'].isnull()] # will handle the missing value with the mean for the years 2015, 2016, 2017 and 2019.

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
19,20,United Arab Emirates,6.774,2.096,0.776,0.67,0.284,0.186,NaN

In [56]:
number = [0.38583, 0.35561, 0.324490, 0.182]
total = sum(number)
count = len(number)
n = total / count
print(n)

0.3119825

In [54]:
df_18["Perceptions of corruption"].fillna(0.3119,inplace=True)

In [9]:
df_19.isnull().sum() # no missing values in 2019

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

#### 7. Check Accuracy:

Verify that the data is correct and precise. This could involve comparing data samples with known sources or using validation rules.

**The process includes:**
1. Validating the appropriateness of data types for the dataset.
2. Identifying outliers  using established validation  rule

In [2]:
# check columns types

In [99]:
df_19.rename(columns={'Overall rank': 'Happiness Rank'}, inplace=True)

In [100]:
df_19.rename(columns={'Score': 'Happiness Score'}, inplace=True)

In [44]:
df_17.rename(columns={'Health..Life.Expectancy.': 'Health (Life Expectancy)'}, inplace=True)

In [46]:
df_17.rename(columns={'Trust..Government.Corruption.': 'Trust (Government Corruption)'}, inplace=True)

In [48]:
df_17.rename(columns={'Dystopia.Residual': 'Dystopia Residual'}, inplace=True)

In [41]:
df_17.rename(columns={'Economy..GDP.per.Capita.': 'Economy (GDP per Capita)'}, inplace=True)

In [8]:
df_18.rename(columns={'Country or region': 'Country'}, inplace=True)

In [10]:
df_19.rename(columns={'Country or region': 'Country'}, inplace=True)

In [27]:
df_17['Region'] = df_17['Country'].map(df_15.set_index('Country')['Region'])

In [12]:
df_18['Region'] = df_18['Country'].map(df_15.set_index('Country')['Region'])

In [23]:
df_19['Region'] = df_19['Country'].map(df_15.set_index('Country')['Region'])

In [29]:
cols = list(df_17.columns)  # Get current column names as a list
cols.insert(1, cols.pop(cols.index('Region')))  
df_17 = df_17[cols]

In [ ]:
cols = list(df_18.columns)  # Get current column names as a list
cols.insert(2, cols.pop(cols.index('Region')))  
df_18 = df_18[cols]

In [25]:
cols = list(df_19.columns)  # Get current column names as a list
cols.insert(2, cols.pop(cols.index('Region')))  
df_19 = df_19[cols]

In [30]:
df_17.head()

,Country,Region,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,Western Europe,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,Western Europe,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,Western Europe,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,Western Europe,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,Western Europe,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [22]:
df_18.head()

,Overall rank,Country,Region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,Western Europe,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,Western Europe,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,Western Europe,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,Western Europe,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [26]:
df_19.head()

,Overall rank,Country,Region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,Western Europe,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,Western Europe,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,Western Europe,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,Western Europe,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [33]:
# go to clean them

In [3]:
# check outliers

In [125]:
selected_columns = [
    'Happiness Rank', 
    'Happiness Score', 
    'Standard Error', 
    'Economy (GDP per Capita)', 
    'Family', 
    'Health (Life Expectancy)', 
    'Freedom', 
    'Trust (Government Corruption)', 
    'Generosity', 
    'Dystopia Residual'
]

# Create a boxplot using Plotly for the selected columns
fig = px.box(df_15, 
             y=selected_columns, 
             title='Boxplot for the World Happiness 2015')

fig.update_layout(
    yaxis_title='Values',
    xaxis_title='Columns',
)

fig.show()

In [124]:
selected_columns = [
    'Happiness Rank', 
    'Happiness Score',  
    'Economy (GDP per Capita)', 
    'Family', 
    'Health (Life Expectancy)', 
    'Freedom', 
    'Trust (Government Corruption)', 
    'Generosity', 
    'Dystopia Residual'
]

# Create a boxplot using Plotly for the selected columns
fig = px.box(df_16, 
             y=selected_columns, 
             title='Boxplot for the World Happiness 2016')

fig.update_layout(
    yaxis_title='Values',
    xaxis_title='Columns',
)

fig.show()

In [123]:
selected_columns = [
    'Happiness Rank', 
    'Happiness Score',  
    'Economy (GDP per Capita)', 
    'Family', 
    'Health (Life Expectancy)', 
    'Freedom', 
    'Trust (Government Corruption)', 
    'Generosity', 
    'Dystopia Residual'
]

# Create a boxplot using Plotly for the selected columns
fig = px.box(df_17, 
             y=selected_columns, 
             title='Boxplot for the World Happiness 2017')

fig.update_layout(
    yaxis_title='Values',
    xaxis_title='Columns',
)

fig.show()

In [121]:
selected_columns = [
    'Happiness Rank', 
    'Happiness Score',  
    'GDP per capita', 
    'Social support', 
    'Healthy life expectancy', 
    'Freedom to make life choices', 
    'Generosity',  
    'Perceptions of corruption'
]

# Create a boxplot using Plotly for the selected columns
fig = px.box(df_18, 
             y=selected_columns, 
             title='Boxplot for the World Happiness 2018')

fig.update_layout(
    yaxis_title='Values',
    xaxis_title='Columns',
)

fig.show()

In [120]:
selected_columns = [
    'Happiness Rank', 
    'Happiness Score',  
    'GDP per capita', 
    'Social support', 
    'Healthy life expectancy', 
    'Freedom to make life choices', 
    'Generosity',  
    'Perceptions of corruption'
]

# Create a boxplot using Plotly for the selected columns
fig = px.box(df_19, 
             y=selected_columns, 
             title='Boxplot for the World Happiness 2019')

fig.update_layout(
    yaxis_title='Values',
    xaxis_title='Columns',
)

fig.show()

**What is an Outlier?** 
Outlier is an row/observation that appears far away and diverges from an overall pattern in a sample.

**What are the types of Outliers?**
1. Univariate: These outliers can be found when we look at distribution of a single variable
2. Multivariate: are outliers in an n-dimensional space. In order to find them, you have to look at distributions in multi-dimensions. example (hight=100, weight=100) for a person

**What causes Outliers?**
Whenever we come across outliers, the ideal way to tackle them is to find out the reason of having these outliers. The method to deal with them would then depend on the reason of their occurrence.

Let’s understand various types of outliers:

1. Data Entry Errors:- Human errors such as errors caused during data collection, recording, or entry can cause outliers in data.
2. Measurement Error: It is the most common source of outliers. This is caused when the measurement instrument used turns out to be faulty.
3. Data Processing Error: Whenever we perform data mining, we extract data from multiple sources. It is possible that some manipulation or extraction errors may lead to outliers in the dataset.
4. Sampling error: For instance, we have to measure the height of athletes. By mistake, we include a few basketball players in the sample. This inclusion is likely to cause outliers in the dataset.
5. Natural Outlier: When an outlier is not artificial (due to error), it is a natural outlier. For instance: In my last assignment with one of the renowned insurance company, I noticed that the performance of top 50 financial advisors was far higher than rest of the population. Surprisingly, it was not due to any error. Hence, whenever we perform any data mining activity with advisors, we used to treat this segment separately.


**What is the impact of Outliers on a dataset?**


![image.png](https://www.analyticsvidhya.com/wp-content/uploads/2015/02/Outlier_31.png)



**How to detect Outliers?**

1. Most commonly used method to detect outliers is visualization (Univariate Graphical Analysis).

We use 3 common visualization methods:
>- Box-plot: A box plot is a method for graphically depicting groups of numerical data through their quartiles. The box extends from the Q1 to Q3 quartile values of the data, with a line at the median (Q2). The whiskers extend from the edges of the box to show the range of the data. Outlier points are those past the end of the whiskers. Box plots show robust measures of location and spread as well as providing information about symmetry and outliers.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:698/format:webp/1*VK5iHA2AB28HSZwWwUbNYg.png)
>
>
>- Histogram
>- Scatter Plot: A scatter plot is a mathematical diagram using Cartesian coordinates to display values for two variables for a set of data. The data are displayed as a collection of points, each having the value of one variable determining the position on the horizontal axis and the value of the other variable determining the position on the vertical axis. The points that are far from the population can be termed as an outlier.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*Ov6aH-8yIwNoUxtMFwgx4g.png)
>
>

2. Using statistical method (Univariate Non-Graphical analysis):
>- Any value, which is beyond the range of -1.5 x IQR to 1.5 x IQR
 
![image.png](https://www.whatissixsigma.net/wp-content/uploads/2015/07/Box-Plot-Diagram-to-identify-Outliers-figure-1.png)

>- Use capping methods. Any value which out of range of 5th and 95th percentile can be considered as outlier
>- Data points, three or more standard deviation away from mean are considered outlier: The Z-score is the signed number of standard deviations by which the value of an observation or data point is above the mean value of what is being observed or measured. While calculating the Z-score we re-scale and center the data and look for data points that are too far from zero. These data points which are way too far from zero will be treated as the outliers. In most of the cases, a threshold of 3 or -3 is used i.e if the Z-score value is greater than or less than 3 or -3 respectively, that data point will be identified as outliers.
> - Outlier detection is merely a special case of the examination of data for influential data points and it also depends on the business understanding

1:What countries or regions rank the highest in overall happiness and each of the six factors contributing to happiness?

In [81]:


# Finding the top countries for each factor
top_countries = df_15.nlargest(10, 'Happiness Score')

# Create a bar chart for overall happiness score
fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_countries['Country'],
    y=top_countries['Happiness Score'],
    name='Happiness Score',
    marker_color='blue'
))

for factor in ['Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 
               'Freedom', 'Trust (Government Corruption)', 'Generosity']:
    fig.add_trace(go.Bar(
        x=top_countries['Country'],
        y=top_countries[factor],
        name=factor,
        marker_color=px.colors.qualitative.Set2[len(fig.data) % len(px.colors.qualitative.Set2)]
    ))

fig.update_layout(
    title='Top Countries in Happiness and Contributing Factors 2015',
    barmode='group',
    xaxis_title='Country',
    yaxis_title='Score',
    legend_title='Factors'
)

fig.show()

In [82]:


# Finding the top countries for each factor
top_countries = df_16.nlargest(10, 'Happiness Score')

# Create a bar chart for overall happiness score
fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_countries['Country'],
    y=top_countries['Happiness Score'],
    name='Happiness Score',
    marker_color='blue'
))

for factor in ['Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 
               'Freedom', 'Trust (Government Corruption)', 'Generosity']:
    fig.add_trace(go.Bar(
        x=top_countries['Country'],
        y=top_countries[factor],
        name=factor,
        marker_color=px.colors.qualitative.Set2[len(fig.data) % len(px.colors.qualitative.Set2)]
    ))

fig.update_layout(
    title='Top Countries in Happiness and Contributing Factors 2016',
    barmode='group',
    xaxis_title='Country',
    yaxis_title='Score',
    legend_title='Factors'
)

fig.show()

In [117]:


# Finding the top countries for each factor
top_countries = df_17.nlargest(10, 'Happiness Score')

# Create a bar chart for overall happiness score
fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_countries['Country'],
    y=top_countries['Happiness Score'],
    name='Happiness Score',
    marker_color='blue'
))

for factor in ['Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 
               'Freedom', 'Trust (Government Corruption)', 'Generosity']:
    fig.add_trace(go.Bar(
        x=top_countries['Country'],
        y=top_countries[factor],
        name=factor,
        marker_color=px.colors.qualitative.Set2[len(fig.data) % len(px.colors.qualitative.Set2)]
    ))

fig.update_layout(
    title='Top Countries in Happiness and Contributing Factors 2017',
    barmode='group',
    xaxis_title='Country',
    yaxis_title='Score',
    legend_title='Factors'
)

fig.show()

In [118]:

# Finding the top countries for each factor
top_countries = df_18.nlargest(10, 'Happiness Score')

# Create a bar chart for overall happiness score
fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_countries['Country'],
    y=top_countries['Happiness Score'],
    name='Happiness Score',
    marker_color='blue'
))

for factor in ['GDP per capita', 'Social support', 'Healthy life expectancy', 
               'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']:
    fig.add_trace(go.Bar(
        x=top_countries['Country'],
        y=top_countries[factor],
        name=factor,
        marker_color=px.colors.qualitative.Set2[len(fig.data) % len(px.colors.qualitative.Set2)]
    ))

fig.update_layout(
    title='Top Countries in Happiness and Contributing Factors 2018',
    barmode='group',
    xaxis_title='Country',
    yaxis_title='Score',
    legend_title='Factors'
)

fig.show()

In [119]:

# Finding the top countries for each factor
top_countries = df_19.nlargest(10, 'Happiness Score')

# Create a bar chart for overall happiness score
fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_countries['Country'],
    y=top_countries['Happiness Score'],
    name='Happiness Score',
    marker_color='blue'
))

for factor in ['GDP per capita', 'Social support', 'Healthy life expectancy', 
               'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']:
    fig.add_trace(go.Bar(
        x=top_countries['Country'],
        y=top_countries[factor],
        name=factor,
        marker_color=px.colors.qualitative.Set2[len(fig.data) % len(px.colors.qualitative.Set2)]
    ))

fig.update_layout(
    title='Top Countries in Happiness and Contributing Factors 2019',
    barmode='group',
    xaxis_title='Country',
    yaxis_title='Score',
    legend_title='Factors'
)

fig.show()

2:How did country ranks or scores change between the 2015 and 2016 as well as the 2016 and 2017 reports?

In [90]:
merged_df = pd.merge(df_15, df_16, on='Country', suffixes=('_2015', '_2016'))


merged_df['Rank Change'] = merged_df['Happiness Rank_2015'] - merged_df['Happiness Rank_2016']
merged_df['Score Change'] = merged_df['Happiness Score_2016'] - merged_df['Happiness Score_2015']
fig = px.scatter(merged_df, 
                 x='Happiness Score_2015', 
                 y='Happiness Score_2016',
                 color='Country',
                 title='Happiness Score Change from 2015 to 2016',
                 labels={
                     'Happiness Score_2015': 'Happiness Score (2015)',
                     'Happiness Score_2016': 'Happiness Score (2016)'
                 })


fig.add_shape(type='line', x0=min(merged_df['Happiness Score_2015']), x1=max(merged_df['Happiness Score_2015']),
              y0=min(merged_df['Happiness Score_2015']), y1=max(merged_df['Happiness Score_2015']),
              line=dict(color='Red', dash='dash'))
fig.show()

In [105]:
merged_df = pd.merge(df_16, df_17, on='Country', suffixes=('_2016', '_2017'))


merged_df['Rank Change'] = merged_df['Happiness Rank_2016'] - merged_df['Happiness Rank_2017']
merged_df['Score Change'] = merged_df['Happiness Score_2017'] - merged_df['Happiness Score_2016']
fig = px.scatter(merged_df, 
                 x='Happiness Score_2016', 
                 y='Happiness Score_2017',
                 color='Country',
                 title='Happiness Score Change from 2016 to 2017',
                 labels={
                     'Happiness Score_2016': 'Happiness Score (2016)',
                     'Happiness Score_2017': 'Happiness Score (2017)'
                 })


fig.add_shape(type='line', x0=min(merged_df['Happiness Score_2016']), x1=max(merged_df['Happiness Score_2016']),
              y0=min(merged_df['Happiness Score_2016']), y1=max(merged_df['Happiness Score_2016']),
              line=dict(color='Red', dash='dash'))
fig.show()

3:Did any country experience a significant increase or decrease in happiness?

In [134]:
merged_df = df_15.merge(df_16, on='Country', suffixes=('_2015', '_2016')) \
                    .merge(df_17, on='Country', suffixes=('', '_2017')) \
                    .merge(df_18, on='Country', suffixes=('', '_2018')) \
                    .merge(df_19, on='Country', suffixes=('', '_2019'))


merged_df['Rank Change 2016-2017'] = merged_df['Happiness Rank_2016'] - merged_df['Happiness Rank']
merged_df['Score Change 2016-2017'] = merged_df['Happiness Score'] - merged_df['Happiness Score_2016']

merged_df['Rank Change 2017-2018'] = merged_df['Happiness Rank'] - merged_df['Happiness Rank']
merged_df['Score Change 2017-2018'] = merged_df['Happiness Score_2018'] - merged_df['Happiness Score']

merged_df['Rank Change 2018-2019'] = merged_df['Happiness Rank'] - merged_df['Happiness Rank']
merged_df['Score Change 2018-2019'] = merged_df['Happiness Score_2019'] - merged_df['Happiness Score']

# Visualize changes in scores over the years for each country
fig = px.line(merged_df, 
              x='Country', 
              y=['Happiness Score_2015', 'Happiness Score_2016', 'Happiness Score', 'Happiness Score_2018', 'Happiness Score_2019'],
              title='Happiness Score Changes from 2015 to 2019',
              labels={'value': 'Happiness Score', 'variable': 'Year'})

fig.show()

Bounce:Saudi Arabia's ranking changed in 2015, 2016, 2017, 2018 and 2019 ?

In [163]:
dataframes = [df_15, df_16, df_17, df_18, df_19]


saudi_arabia_ranks = [df['Happiness Rank'][df['Country'] == 'Saudi Arabia'].values[0] for df in dataframes]


fig = go.Figure(data=[go.Bar(x=['2015', '2016', '2017', '2018', '2019'],
                             y=saudi_arabia_ranks,
                             marker_color='skyblue')])

fig.update_layout(title='Saudi Arabia Ranking Over Time',
                  xaxis_title='Year',
                  yaxis_title='Saudi Arabia Rank')

fig.show()